// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE4rrlMFDsSDevTTnZn9HANs8LUARkwLU',
    appId: '1:439337441830:web:b73b7e1156f52e9682a4e7',
    messagingSenderId: '439337441830',
    projectId: 'purchaso-bbi',
    authDomain: 'purchaso-bbi.firebaseapp.com',
    storageBucket: 'purchaso-bbi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_hHjFfbep8LUScNvghRgt8oJZ6JbYUSQ',
    appId: '1:439337441830:android:daa3daa1a128788c82a4e7',
    messagingSenderId: '439337441830',
    projectId: 'purchaso-bbi',
    storageBucket: 'purchaso-bbi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY_CdDhHWHh4XCgSMr_AGrYDgWyby8kyQ',
    appId: '1:439337441830:ios:2efb9777a13ebc4582a4e7',
    messagingSenderId: '439337441830',
    projectId: 'purchaso-bbi',
    storageBucket: 'purchaso-bbi.firebasestorage.app',
    iosBundleId: 'com.example.purchaso',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY_CdDhHWHh4XCgSMr_AGrYDgWyby8kyQ',
    appId: '1:439337441830:ios:2efb9777a13ebc4582a4e7',
    messagingSenderId: '439337441830',
    projectId: 'purchaso-bbi',
    storageBucket: 'purchaso-bbi.firebasestorage.app',
    iosBundleId: 'com.example.purchaso',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE4rrlMFDsSDevTTnZn9HANs8LUARkwLU',
    appId: '1:439337441830:web:89b7122436a119d882a4e7',
    messagingSenderId: '439337441830',
    projectId: 'purchaso-bbi',
    authDomain: 'purchaso-bbi.firebaseapp.com',
    storageBucket: 'purchaso-bbi.firebasestorage.app',
  );
}
