// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACcKJzDlvMqgI809OGvUx6B_CrT1Zc4Nw',
    appId: '1:840746386028:web:22c277193c2f0e37cd4e49',
    messagingSenderId: '840746386028',
    projectId: 'task-manager-firebase-4a74f',
    authDomain: 'task-manager-firebase-4a74f.firebaseapp.com',
    storageBucket: 'task-manager-firebase-4a74f.firebasestorage.app',
    measurementId: 'G-61GNG4NKDG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7eF5vPfsW_I9DUgjAqesUodf5hEdYSVQ',
    appId: '1:840746386028:android:878bc57573e6271fcd4e49',
    messagingSenderId: '840746386028',
    projectId: 'task-manager-firebase-4a74f',
    storageBucket: 'task-manager-firebase-4a74f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-OBAVMDkFJ7_xPHRmtN2ywQ8fDETL0Uo',
    appId: '1:840746386028:ios:e3cb963b4f63f642cd4e49',
    messagingSenderId: '840746386028',
    projectId: 'task-manager-firebase-4a74f',
    storageBucket: 'task-manager-firebase-4a74f.firebasestorage.app',
    iosBundleId: 'com.example.taskManagerFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-OBAVMDkFJ7_xPHRmtN2ywQ8fDETL0Uo',
    appId: '1:840746386028:ios:e3cb963b4f63f642cd4e49',
    messagingSenderId: '840746386028',
    projectId: 'task-manager-firebase-4a74f',
    storageBucket: 'task-manager-firebase-4a74f.firebasestorage.app',
    iosBundleId: 'com.example.taskManagerFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACcKJzDlvMqgI809OGvUx6B_CrT1Zc4Nw',
    appId: '1:840746386028:web:8e739c7e29a16c9ccd4e49',
    messagingSenderId: '840746386028',
    projectId: 'task-manager-firebase-4a74f',
    authDomain: 'task-manager-firebase-4a74f.firebaseapp.com',
    storageBucket: 'task-manager-firebase-4a74f.firebasestorage.app',
    measurementId: 'G-DQQ6YHDYC5',
  );
}
